import Section from "../components/Section";
import SEO from "../components/SEO";

export default function Privacy() {
  return (
    <>
      <SEO title="Privacy Policy" description="How KnowYourAI collects, uses, stores, and protects your data." path="/privacy" />
      <Section eyebrow="Legal" title="Privacy Policy" description="Last updated: June 2026" />

      <section className="section">
        <div style={{ maxWidth: "72ch", margin: "0 auto" }} className="prose-legal">

        <h2>1. Introduction</h2>
        <p>This Privacy Policy describes how KnowYourAI, the independent project that operates knowyourai.live ("KnowYourAI," "we," "us," or "our") collects, uses, discloses, and protects information when you use our website, services, tools, and APIs (collectively, the "Services"). By accessing or using the Services, you acknowledge that you have read and understood this Privacy Policy.</p>

        <h2>2. Information We Collect</h2>

        <h3>2.1 Information You Provide</h3>
        <ul>
          <li><strong>Account information:</strong> Name, email address, company name, and authentication credentials when you create an account</li>
          <li><strong>Assessment request information:</strong> Contact details, company name, system descriptions, and concerns submitted through our assessment request form</li>
          <li><strong>Scan configurations:</strong> API endpoints, use case descriptions, allowed/disallowed capabilities, language preferences, and other parameters you configure for testing</li>
          <li><strong>Communications:</strong> Content of messages you send to us through contact forms or email</li>
        </ul>

        <h3>2.2 Information Generated Through Use</h3>
        <ul>
          <li><strong>Scan results and reports:</strong> Outputs, findings, violation data, risk scores, and evidence generated by the Services when processing your configurations</li>
          <li><strong>Enforcement logs:</strong> Intent classification results, policy decisions, and routing logs generated by IntentEnforce</li>
          <li><strong>Usage data:</strong> Service interaction patterns, feature usage, timestamps, and session data</li>
        </ul>

        <h3>2.3 Automatically Collected Information</h3>
        <ul>
          <li><strong>Device and browser information:</strong> Browser type, operating system, device identifiers, and screen resolution</li>
          <li><strong>Log data:</strong> IP addresses, access times, pages viewed, and referring URLs</li>
          <li><strong>Cookies and similar technologies:</strong> As described in our Cookie Policy</li>
        </ul>

        <h2>3. How We Use Information</h2>
        <p>We use the information we collect to:</p>
        <ul>
          <li>Provide, operate, and maintain the Services</li>
          <li>Process and fulfill assessment requests</li>
          <li>Generate scan results, reports, and enforcement decisions</li>
          <li>Authenticate users and manage accounts</li>
          <li>Communicate with you about the Services, including responding to inquiries</li>
          <li>Monitor and improve the reliability, security, and performance of the Services</li>
          <li>Detect, prevent, and address fraud, abuse, and security issues</li>
          <li>Comply with legal obligations</li>
        </ul>

        <h2>4. How We Share Information</h2>
        <p>We do not sell your personal information. We may share information in the following limited circumstances:</p>
        <ul>
          <li><strong>Service providers:</strong> With third-party providers who assist in operating the Services (e.g., cloud hosting, email delivery), subject to confidentiality obligations</li>
          <li><strong>Legal requirements:</strong> When required by law, regulation, legal process, or governmental request</li>
          <li><strong>Protection of rights:</strong> When necessary to protect our rights, safety, or property, or that of our users or the public</li>
          <li><strong>Business transfers:</strong> In connection with a merger, acquisition, or sale of assets, subject to appropriate confidentiality protections</li>
          <li><strong>With your consent:</strong> When you have given explicit consent to share specific information</li>
        </ul>

        <h2>5. Data Retention</h2>
        <p>We retain information for as long as necessary to provide the Services and fulfill the purposes described in this Privacy Policy, unless a longer retention period is required or permitted by law. Scan data and reports are retained for the duration of your account unless you request earlier deletion. Upon account termination, we will delete or anonymize your data within a reasonable period, subject to any legal retention obligations.</p>

        <h2>6. Data Security</h2>
        <p>We implement reasonable technical and organizational measures to protect information against unauthorized access, alteration, disclosure, or destruction. However, no method of transmission over the internet or electronic storage is completely secure. We cannot guarantee absolute security, and you acknowledge that you transmit data at your own risk.</p>

        <h2>7. Your Rights</h2>
        <p>Depending on your jurisdiction, you may have certain rights regarding your personal information, including the right to:</p>
        <ul>
          <li>Access the personal information we hold about you</li>
          <li>Request correction of inaccurate information</li>
          <li>Request deletion of your personal information</li>
          <li>Object to or restrict certain processing</li>
          <li>Request data portability</li>
          <li>Withdraw consent where processing is based on consent</li>
        </ul>
        <p>To exercise any of these rights, please contact us through the contact information on our website. We will respond to your request within a reasonable timeframe and in accordance with applicable law.</p>

        <h2>8. International Data Transfers</h2>
        <p>Your information may be processed and stored in jurisdictions other than your own. By using the Services, you consent to the transfer of your information to India and other countries where we or our service providers operate. We take reasonable steps to ensure that your data is treated securely and in accordance with this Privacy Policy.</p>

        <h2>9. Third-Party Services</h2>
        <p>The Services may contain links to third-party websites or integrate with third-party services. We are not responsible for the privacy practices of any third party. We encourage you to review the privacy policies of any third-party services you access through or in connection with our Services.</p>

        <h2>10. Children's Privacy</h2>
        <p>The Services are not directed to individuals under the age of 18. We do not knowingly collect personal information from children. If we become aware that we have collected personal information from a child, we will take steps to delete such information promptly.</p>

        <h2>11. Changes to This Policy</h2>
        <p>We may update this Privacy Policy from time to time. We will post the updated policy on our website with a revised "Last updated" date. Your continued use of the Services after any changes constitutes acceptance of the updated Privacy Policy.</p>

        <h2>12. Governing Law</h2>
        <p>This Privacy Policy shall be governed by and construed in accordance with the laws of India. Any disputes arising from this Privacy Policy shall be subject to the exclusive jurisdiction of the courts located in Mysore (Mysuru), Karnataka, India.</p>

        <h2>13. Contact</h2>
        <p>Questions or concerns about this Privacy Policy may be directed to us through the contact information provided on our website.</p>

        </div>
      </section>
    </>
  );
}
