from __future__ import annotations

import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


def generate_scan_pdf(scan_record: dict) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=20 * mm, bottomMargin=20 * mm)
    styles = getSampleStyleSheet()
    elements = []

    title_style = ParagraphStyle("Title", parent=styles["Title"], fontSize=20, spaceAfter=6)
    heading_style = ParagraphStyle("Heading", parent=styles["Heading2"], fontSize=14, spaceBefore=12, spaceAfter=6)
    body_style = styles["BodyText"]

    elements.append(Paragraph("KnowYourAI — IntentScan Report", title_style))
    elements.append(Spacer(1, 4 * mm))

    config = scan_record.get("config", {})
    summary = scan_record.get("summary", {})
    violations = scan_record.get("violations", [])
    created = scan_record.get("created_at", "")

    # Meta
    meta_data = [
        ["Date", created[:19] if created else "—"],
        ["Target", str(config.get("api_url", "—"))],
        ["Tests Run", str(summary.get("total_tests", 0))],
        ["Violations Found", str(summary.get("violations", 0))],
    ]
    meta_table = Table(meta_data, colWidths=[100, 350])
    meta_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    elements.append(meta_table)
    elements.append(Spacer(1, 6 * mm))

    # Risk score
    risk = summary.get("risk_score", 0)
    risk_color = colors.green if risk < 40 else colors.orange if risk < 70 else colors.red
    elements.append(Paragraph("Risk Assessment", heading_style))
    risk_data = [["Risk Score", f"{risk:.1f} / 100"]]
    risk_table = Table(risk_data, colWidths=[100, 350])
    risk_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 14),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
        ("TEXTCOLOR", (1, 0), (1, 0), risk_color),
    ]))
    elements.append(risk_table)
    elements.append(Spacer(1, 6 * mm))

    # Violations
    if violations:
        elements.append(Paragraph("Violations", heading_style))
        for i, v in enumerate(violations):
            analysis = v.get("analysis", {})
            sev = analysis.get("severity", "low")
            sev_color = {"critical": colors.red, "high": colors.orangered, "medium": colors.orange}.get(sev, colors.green)

            elements.append(Paragraph(
                f"<b>#{i+1}</b> — {analysis.get('type', 'unknown')} "
                f"(<font color='{sev_color.hexval()}'>{sev}</font>, "
                f"confidence: {analysis.get('confidence', 0):.0%})",
                body_style,
            ))
            elements.append(Paragraph(f"<b>Strategy:</b> {v.get('strategy', '—')}", body_style))
            elements.append(Paragraph(f"<b>Probe:</b> {_escape(v.get('prompt', ''))[:300]}", body_style))
            elements.append(Paragraph(f"<b>Reason:</b> {_escape(analysis.get('reason', ''))}", body_style))
            elements.append(Spacer(1, 4 * mm))
    else:
        elements.append(Paragraph("No violations detected.", body_style))

    elements.append(Spacer(1, 10 * mm))
    elements.append(Paragraph(
        "<i>Generated by KnowYourAI IntentScan. This report is for informational purposes.</i>",
        ParagraphStyle("Footer", parent=body_style, fontSize=8, textColor=colors.gray),
    ))

    doc.build(elements)
    return buf.getvalue()


def _escape(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
